# Generated by Django 3.1.3 on 2020-11-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201115_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
